Handle interrupted error from mio
notify-rs/notify pull request #281
Opened 2021-02-14 01:54 UTC by rschoon

Mio 0.7 was changed to no longer automatically retry on system call interruption, so we now must do it ourselves.  For example, the process receiving SIGINT could cause notify to panic, if the signal handler had been changed from default:
```
thread '<unnamed>' panicked at 'poll failed: Os { code: 4, kind: Interrupted, message: "Interrupted system call" }', /home/rschoon/.cargo/registry/src/github.com-1ecc6299db9ec823/notify-5.0.0-pre.5/src/inotify.rs:134:47
```

2021-02-14 17:53 UTC, 0xpr03 reviewed
Could we test this somehow in CI ?

2021-02-14 22:54 UTC, rschoon commented
Probably, although getting it right seems like it might be a bit complicated.  Doing it as an integration test and sending a signal to its own pid would probably be sufficient to exercise the problem, but verifying things went according to plan might be harder.

2021-02-15 12:07 UTC, 0xpr03 requested changes

2021-02-15 12:07 UTC, 0xpr03 commented on src/inotify.rs
> +                    // System call was interrupted, we will retry
I'd like to land this but not loose the information, could you just document in the comment that there is no actual test for this ?

2021-02-15 12:43 UTC, 0xpr03 approved these changes

2021-02-16 07:25 UTC, JohnTitor approved these changes
LGTM, I think it's worth mentioning this in the changelog, could you add an entry?

@0xpr03 Feel free to merge once it's done :)

2021-02-20 00:11 UTC, merged

2021-02-20 00:11 UTC, 0xpr03 commented
Thanks for tackling this !