Change EventFn to take FnMut
notify-rs/notify pull request #333
Opened 2021-06-08 04:15 UTC by erickt

This changes EventFn to work with FnMut, rather than Fn. The advantage of this is that this allows callers to use state in the EventFn, rather than having to use interior mutability. This is helpful particularly for getting notify to work with async rust, since `futures::channel::mpsc`'s methods all take `&mut self`.

The downside of this change is that it limits the ability of notify to share `EventFn` across multiple threads, but all the backends either guarantee only a single background thread, or they already use an `Arc<Mutex<...>>` to protect `EventFn`.

2021-06-08 09:21 UTC, 0xpr03 requested changes
> but all the backends either guarantee only a single background thread, or they already use an Arc<Mutex<...>> to protect EventFn

That looks fine but can/do we somehow guarantee/note that we now expect only a single Fn caller at any point in time in the backends?

2021-06-08 09:30 UTC, 0xpr03 commented
Also thanks for all the changes. Based on your contributions, do you maybe want to be part of the team to maintain this crate, especially since you seem to have an apple device to test the fsevent part ?

2021-06-08 14:53 UTC, erickt commented
> That looks fine but can/do we somehow guarantee/note that we now expect only a single Fn caller at any point in time in the backends?

That should be implied by using `FnMut`, which will guarantee only one caller unless we make a mistake with `unsafe` and alias the function pointer. I looked through our use of `EventFn`, and it looks like all watchers but `INotifyWatcher` wrap their `event_fn` in `Arc<Mutex<...>>`. `INotifyWatcher` can get away with it only ever uses one background thread, so it can transfer ownership of the `EventFn` into it. We could change all the other watchers to use this pattern, which I think would allow us to get rid of the mutex.

> Also thanks for all the changes. Based on your contributions, do you maybe want to be part of the team to maintain this crate, especially since you seem to have an apple device to test the fsevent part ?

Thanks for the offer! I can try to help here and there, but I don't think I can commit to maintenance at this time. I think with these last couple changes addresses all my needs, and I can unblock my actual use of notify :)

2021-06-09 12:05 UTC, 0xpr03 commented
> We could change all the other watchers to use this pattern, which I think would allow us to get rid of the mutex.

I think we'll leave that for a later PR and merge this one in the meantime.

> I think with these last couple changes addresses all my needs, and I can unblock my actual use of notify 

No problem, let's see when your next issue comes up ;)

2021-06-09 12:05 UTC, 0xpr03 approved these changes

2021-06-09 12:05 UTC, merged