Add `EventHandler` trait to replace `EventFn`
notify-rs/notify pull request #346
Opened 2021-08-06 16:03 UTC by a1phyr

Replace `EventFn`trait with `EventHandler`.

The new trait has new capabilities but can be implemented for more types, such as channel receivers which are very commonly used.

2021-08-08 06:26 UTC, 0xpr03 requested changes
Hi, can you rebase this onto the current master ? Other than that it seems fine, except for more documentation.

2021-08-08 06:26 UTC, 0xpr03 commented on src/lib.rs
>  /// The set of requirements for watcher event handling functions.
Can you add an example in the documentation for using the new impls ?

2021-08-08 15:17 UTC, a1phyr commented
Done

2021-08-12 19:26 UTC, 0xpr03 commented
Thanks! I'll add an example to the lib file. Maybe it'll be worth wile to add a tokio feature where we also implement this for async tokio channels. Problem is though, that we'll have to select between tokio::sync::broadcast and tokio::sync::watch or tokio::sync::mpsc.

2021-08-12 19:27 UTC, merged