code style improvement
notify-rs/notify pull request #538
Opened 2023-10-01 15:38 UTC by coswat

* added `Self` instead of hardcoded impl name -> in notify crate
* organized imports -> in notify crate
* `eprintln!()` macro for Error printing instead of normal println macro -> in file-id crate

2023-10-02 21:36 UTC, 0xpr03 requested changes
I would leave the `Self` parts for now, unless you want to use these changes to get towards a bigger feature. Adding only changes for subjective code readability is sadly adding git log/blame noise.

2023-10-02 21:36 UTC, 0xpr03 commented on file-id/src/lib.rs
> +        Self::Inode {
I think replacing the Name with Self is only reducing readability and doesn't really remove any duplication (FileId -> Self) when you use also `use FileId::*;` and drop the prefix completely. Either way I think it's fine as it is.

2023-10-02 21:36 UTC, 0xpr03 commented on file-id/bin/file_id.rs
> +        Err(error) => eprintln!("Error: {error}"),
I mean, you can do that but this is just an example, so it won't matter at all. (Also there is an unrelated import change in that commit.)

2023-10-03 02:01 UTC, coswat commented
oh ok

2023-10-03 02:11 UTC, closed without merging