Prevent installing `crossbeam-channel` with `default-features="false"`
notify-rs/notify pull request #550
Opened 2023-11-22 16:57 UTC by LeoniePhiline

Debouncers used to install `crossbeam-channel`,
due to keeping `notify`'s default features enabled
even if their own default features were disabled.

With this change, `crossbeam-channel` will
no longer be installed if `notify-debouncer-*`
as well as `notify` are installed with
`default-features = false`

Fixes #549

2023-11-23 11:25 UTC, LeoniePhiline commented
Thanks for running the workflow!

I have [adjusted](https://github.com/notify-rs/notify/compare/9a8176a77dd2fa8e81e69899d1e7cedc64d98ded..1d02f8bc14f1feba57991f43a781e9136192bec3) the pull request with the following:

- Allow both `macos_fsevent` and `macos_kqueue` features to be forwarded from debouncer crates to their `notify` dependency.
- Forward `macos_fsevent` to `notify` by default, as is `notify`'s default feature set.
- Adjust the `README` of both debouncers to mention enabling a backend of choice on MacOS if default features are disabled.
- Adjust `notify-debouncer-mini`'s `README` formatting to match `notify-debouncer-full`'s `README`.
- Adjust the github workflow to check debouncers with both MacOS backends forwarded as feature flags to `notify`.
- Align github workflow job names in regards to disabled features. (Align debouncer feature check job names with `notify` feature check job names.)

2023-11-24 09:21 UTC, LeoniePhiline commented
[Workflow run **643**](https://github.com/notify-rs/notify/actions/runs/6969015177) can be cancelled. See intermediate version [missing a job condition predicate](https://github.com/notify-rs/notify/compare/1d02f8bc14f1feba57991f43a781e9136192bec3..ab0c6fd26a8d0a3820b9cf96dcaebf20b0e3cfa1).

[Workflow run **644**](https://github.com/notify-rs/notify/actions/runs/6969086309 ) can be run.

2023-11-28 22:04 UTC, 0xpr03 requested changes
Looks good overall. I've left some comment.

In any case thanks for the work, especially regarding streamlining docs.

2023-11-28 22:04 UTC, 0xpr03 commented on notify-debouncer-full/Cargo.toml
> +macos_fsevent = ["notify/macos_fsevent"]
Is there a reason for masquerading the notify features? We simply let user specify them in their own cargo toml until now.

2023-11-28 22:05 UTC, 0xpr03 commented
This will be part of #525

2024-01-04 20:14 UTC, 0xpr03 approved these changes

2024-01-04 20:14 UTC, merged