Fix unaligned access to FILE_NOTIFY_INFORMATION
notify-rs/notify pull request #647
Opened 2024-10-21 04:41 UTC by ruihe774

In some environments (e.g. wine), `FILE_NOTIFY_INFORMATION` is packed placed and is unaligned. Reading from unaligned `FILE_NOTIFY_INFORMATION` is a UB and causes panics in debug builds. This PR workarounds this issue by using `ptr::read_unaligned`.

2024-10-23 19:25 UTC, dfaust requested changes
Thanks for the PR. Looks good to me, but please add some more comments. This is an edge case that probably nobody working on this code will have on their radar.

2024-10-23 19:25 UTC, dfaust commented on notify/src/windows.rs
> +            // In theory accesing to u16 can also be misaligned, but in reality it is never
Spelling

2024-10-25 07:55 UTC, dfaust commented
Thanks. Unfortunately `offset_of` has only been stabilized in Rust 1.77 and our MSRV is 1.72.
My suggestion: I'm going to branch off and release a new version today and then merge this PR into `main` afterwards.

CC: @0xpr03 @JohnTitor

2024-10-25 10:35 UTC, ruihe774 commented
> Thanks. Unfortunately `offset_of` has only been stabilized in Rust 1.77 and our MSRV is 1.72. My suggestion: I'm going to branch off and release a new version today and then merge this PR into `main` afterwards.
> 
> CC: @0xpr03 @JohnTitor

We can hard code it giving `FILE_NOTIFY_INFORMATION` has a stable ABI; somewhat dirty, though.

2024-11-24 19:46 UTC, merged